[build]
  command = "cd backend && npm ci && npm run build && cd ../frontend && npm ci && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/dist/netlify/functions"
  node_bundler = "esbuild"
  ignored_node_modules = [
    "@nestjs/microservices",
    "@nestjs/websockets"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200